---
# Only version in the apt policy of the vm at this time
pg_version: "14"

package_list:
  - acl
  - "postgresql-{{ pg_version }}"
  - "postgresql-contrib-{{ pg_version }}"
  - python3-psycopg2

service_name: postgresql
pg_conf_dir: "/etc/postgresql/{{ pg_version }}/main"

linux_group_name: cytech_grp
linux_user_name: cytech_usr

pg_port: 5432
pg_max_connections: 100
pg_hba_conf_src: pg_hba.conf.j2
pg_hba_conf_dest: "{{ pg_conf_dir }}/pg_hba.conf"
pg_conf_src: postgresql.conf.j2
pg_conf_dest: "{{ pg_conf_dir }}/postgresql.conf"
pg_username: postgres
pg_db_username: cytech_usr
pg_db_name: cytech

template_files_permissions: "0640"
